### ISSUE TITLE
show.diag=FALSE not working

### ISSUE THREAD

**Issue by arbet003** [kassambara/ggcorrplot#31]
Hello,

I am trying to produce a heatmap where the diagonal correlations are removed, using show.diag=FALSE.   However, the following code produces identical results regardless of show.diag=T or F:

```
library("ggcorrplot")
data(mtcars)
cormat=cor(mtcars)
ggcorrplot(cormat, hc.order = TRUE, type = "full"
           ,tl.cex=8,outline.color="#f0f0f000",show.diag = F)

ggcorrplot(cormat, hc.order = TRUE, type = "full"
           ,tl.cex=8,outline.color="#f0f0f000",show.diag = T)
```

**Comment by IndrajeetPatil** [comment]
Yeah, I can reproduce this behavior:

``` r
library("ggcorrplot")
#> Loading required package: ggplot2
data(mtcars)
cormat=cor(mtcars)
ggcorrplot(cormat, hc.order = TRUE, type = "full", lab = TRUE,
           ,tl.cex=8,outline.color="#f0f0f000",show.diag = F)
```

![](https://i.imgur.com/HtiGZ0R.png)

``` r

ggcorrplot(cormat, hc.order = TRUE, type = "full", lab = TRUE,
           ,tl.cex=8,outline.color="#f0f0f000",show.diag = T)
```

![](https://i.imgur.com/Pp4vkM3.png)

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kassambara** [comment]
fixed now, thank you!

**Comment by IndrajeetPatil** [comment]
Cool, thanks!

Feel free to close this.

**Comment by arbet003** [comment]
Hello,

Thank you for your help with this.  I am still having some issues with the show.diag option (after installing latest github version of package).  Please consider the following code:

```
data(mtcars)

cormat=cor(mtcars)
ggcorrplot(cormat, hc.order = TRUE,tl.cex=8,show.diag=T)
ggcorrplot(cormat, hc.order = TRUE,tl.cex=8,show.diag=F)
```

The 2nd plot adds X's to many of the correlations although I did not supply a p-value matrix.  There seems to be a bug here?

Thanks

**Comment by kassambara** [comment]
fixed now, thank you
